
spring:
  main:
    banner-mode: off

    spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traffic_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
   # show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      #  format_sql: true
  sql:
    init:
      mode: always

      traffic:
        scheduler:
          rotation-time: 60000

server:
  port: 8080
